parameters:
- name: image
  displayName: 'Pool image'
  default: ubuntu-latest
  values:
  - windows-latest
  - windows-latest
  - ubuntu-latest
  - ubuntu-latest
  - macOS-latest
  - macOS-latest
- name: test
  displayName: Run Tests?
  type: boolean
  default: false

variables:
- name: testEmpty
  value: ''

pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
  - job: A1
    steps:
      - script: echo Hello Stage A!
- stage: B
  jobs:
  - job: AB1
    steps:
    - bash: |
        echo "This is job AB1."
        echo "##vso[task.setvariable variable=doThing;isOutput=true]Yes" #set variable doThing to Yes
      name: DetermineResult
  - job: BB1
    dependsOn: AB1
    condition: eq(dependencies.AB1.outputs['DetermineResult.doThing'], 'Yes') #map doThing and check the value
    steps:
    - script: echo "Job AB1 ran and doThing is Yes."
    