parameters:
- name: image
  displayName: 'Pool image'
  default: ubuntu-latest
  values:
  - windows-latest
  - windows-latest
  - ubuntu-latest
  - ubuntu-latest
  - macOS-latest
  - macOS-latest
- name: test
  displayName: Run Tests?
  type: boolean
  default: false
- name: doThing
  default: true
  type: boolean

variables:
- name: testEmpty
  value: ''

pool:
  vmImage: ubuntu-latest

stages:
- stage: A
  jobs:
  - job: A1
    steps:
      - script: echo Hello Stage A!
- stage: B
  jobs:
  - job: B1
    steps:
    - script: echo I did a thing
      condition: and(succeeded(), ${{ eq(parameters.doThing, true) }})
    